### ISSUE TITLE
Missing dependency on Ubuntu 22.04

### ISSUE THREAD

**Issue by sblandford** [PhantomSDR/PhantomSDR#1]
libvolk2-dev is required for ninja to complete. Please add to the apt install in the build instructions.

**Comment by rhgndf** [comment]
I have removed for the dependence on volk in efeb019. If you decide to host one please do tell! I add it to a receiver map.

**Comment by sblandford** [comment]
Fixed the issue, thanks. I can't promise I will host an instance any time soon. I am just curious at this stage to see what it does, but I will definitely be introducing other SWL/HAMs to it as soon as I can demo it.

**Comment by rhgndf** [comment]
No issues about that! It would be better for discoverability if there was a receiver map is what I am suggesting. Thanks for your support of this software by demonstrating it to others!
