### ISSUE TITLE
Add SDRPlay to Wiki

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/PhantomSDR#10]
Using https://github.com/SDRplay/RSPTCPServer
and netcat we can use an SDRPlay RSP. Use 16 bit otherwise its very bad. This can be done by i think using "rsp_tcp -f frequencyhere -b 16". I tried it, works fine.

**Comment by Steven9101** [comment]
Just saw you used rx_sdr, thats even smarter. If it can deliver 16 bit

**Comment by rhgndf** [comment]
miri_sdr is even better. Will add it to the wiki.

**Comment by rhgndf** [comment]
wiki/Configuration-MiriSDR

**Comment by Steven9101** [comment]
Thanks
