### ISSUE TITLE
Get Waterfall more responsive when dragging

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/PhantomSDR#12]
Cant we get the waterfall more responsive when dragging? Im thinking of it as i got told by friend if he drags by multiple Mhz it isnt as responsive, maybe the waterfall is the big on the website? Im unsure if its the data coming to slow or the waterfall drawing to slow. I think the data is fast enough. Should be atleast. I opened it in main repo here as im unsure if its either data or the html. Ill take a look at it now.

**Comment by rhgndf** [comment]
I have reduced the waterfall buffering to a minimum, this should help with the responsiveness, but the waterfall might be a bit jittery when the network conditions are bad. I think this could be a good tradeoff since responsiveness is more important.

**Comment by Steven9101** [comment]
Btw, when using the mouse wheel the frequency selector shows the wrong frequency but sets the correct one

**Comment by Steven9101** [comment]
when scrolling up from 5505 to 6505 it goes to 6505 but shows 7505

**Comment by rhgndf** [comment]
This should be fixed in the latest commit also, I also caught that.

**Comment by Steven9101** [comment]
Thank you! 👍 

I updated the sdr list to use SSL also!

**Comment by Steven9101** [comment]
Waterfall feels way more responsive now also, thanks alot!
