### ISSUE TITLE
Incorrect information and link in Receiver List page

### ISSUE THREAD

**Issue by sblandford** [PhantomSDR/PhantomSDR#14]
I have a test setup on https://phantomsdr.simonb.org.uk. It covers 27.280 MHz to 28.719 MHz.

However the frequency range on https://phantomsdr.github.io/servers is incorrectly reported as 28.000 MHz to 29.440 MHz and the although the link is visibly correct, phantomsdr.simonb.org.uk, it actually links to https://_phantomsdr.github.io_/phantomsdr.simonb.org.uk when clicked.

Here is the config.toml file I am using.
```
[server]
port=9002 # Server port
html_root="html-svelte/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable

[register]
enable=true
name="G7GSF"
antenna="Boni Whip"
description="10m & CB band on Nooelec stick"
url="phantomsdr.simonb.org.uk"

[input]
sps=1440000 # Input Sample Rate
fft_size=131072 # FFT bins
frequency=28000000 # Baseband frequency
signal="iq" # real or iq
accelerator="none" # Accelerator: none, cuda, opencl
audio_sps=48000 # Audio Sample Rate

[input.driver]
name="stdin" # Driver name
format="u8" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=28074000 # Default frequency to show user
modulation="USB" # Default modulation
```

**Comment by rhgndf** [comment]
For the url, you would need it to add https:// in front of it: like this: url="https://phantomsdr.simonb.org.uk"
This is needed or else the browser won't know whether to use http or https.

Also documented one more config option in the docs, where you can specify your hardware (optional).

Added both into the wiki!

**Comment by rhgndf** [comment]
I am investigating the issue now, also I would like to fix the black waterfall areas issue at the same time too

**Comment by sblandford** [comment]
OK thanks. I can see that the link is fixed when I added the https:// to it. Although it did have redirection from http to https.

**Comment by rhgndf** [comment]
Have fixed the wrong frequency issue.

I have added one more config option brightness_offset. This looks dependent per SDR, so one would need to tune it a bit. Try values from -1 to -10. For your case, a smaller value like -1 to -5 would work.

**Comment by sblandford** [comment]
I got a nice blue background on the waterfall now with brightness_offset=-15. Thank you for adding this feature.
