### ISSUE TITLE
RX888MK2 config example ?

### ISSUE THREAD

**Issue by nmaster2042** [PhantomSDR/PhantomSDR#3]
Is there a config example for the RX888MK2 to work wgit this web SDR ?

**Comment by rhgndf** [comment]
The example config is in the wiki:
https://github.com/PhantomSDR/PhantomSDR/wiki/Configuration-RX888

Either use a GPU for the processing, or make sure that the CPU is powerful enough. If using CPU, set the fft_threads to the number of CPU cores.

**Comment by nmaster2042** [comment]
Sorry, I missed the wiki part, thank you very much.
