### ISSUE TITLE
SSB Sound weird for LSB

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/PhantomSDR#5]
LSB Sounds weird (stutters) while USB works fine. Looking at the code atm to find out why but unsure right now

**Comment by rhgndf** [comment]
What SDR are you using? Is it a real input or IQ input?

**Comment by Steven9101** [comment]
Hi, i tried both on RX888 Mk ii and on an rtl sdr. Both have this issue

**Comment by Steven9101** [comment]
Btw i really appreciate this project and ill 100% sure host an sdr and also contribute, just cant seem to find out what is causing the lsb to sound like this.

**Comment by Steven9101** [comment]
Its easy to test, just find somebody talking on lsb and hear how it sounds. USB, AM, FM etc work fine.

**Comment by rhgndf** [comment]
Unfortunately it is a known bug, I still do not understand the bug fully to fix it properly. In the meantime, removing the DC component by moving the passband away from the DC could help a bit.

**Comment by Steven9101** [comment]
Yea i also looked at the code and cant figure out why its only on LSB and not on USB, i mean its just inversed. But its just repeating the audio so i cant even hear it properly its just stuttering weirdly, ill try what you said.

**Comment by rhgndf** [comment]
I'll try investigate more, I have some ideas on why it is happening.

**Comment by Steven9101** [comment]
Really appreciate it, keep me updated. Ill be doing PRs once thats fixed to add more features etc. This is by far the best WebSDR software out there right now.

**Comment by rhgndf** [comment]
Try this: f02f1f2

**Comment by Steven9101** [comment]
Appears to be fixed, just getting my antenna up to try it on 40m

**Comment by rhgndf** [comment]
It seems to work on both IQ input and real input, so this problem might be solved.

**Comment by Steven9101** [comment]
Yep, its solved. You are a legend thank you so much!

**Comment by rhgndf** [comment]
Anyways, thanks for your support of this software! You could also help by telling others about this.

**Comment by Steven9101** [comment]
Ill surely do that, ill host an WebSDR with this software surely to cover the whole HF Band. Just getting everything ready probably making some GUI Changes adding some stuff and then using my Server with a GPU to cover the whole band!

**Comment by rhgndf** [comment]
Nice! I'll try to get a receiver list website up soon.

**Comment by Steven9101** [comment]
Sounds nice, after some more listening it sounds good. Only thing i have noticed now is probably the AGC or something kicking in after a short period of time and just being extremly loud. That ill have to look into, wont be to hard i guess. When loading the site in i mean it takes a bit of time and then its probably applying gain or AGC.
