### ISSUE TITLE
Underrun

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/PhantomSDR#6]
Got my setup up now from 0MHz to 50Mhz working fine with GPU, it can handle many users with no high load (could probably handle 200-400 users easily). But i found one issue out again (hopefully i dont disturb you much. just trying to get this perfected as much as possible). I get one underrun and then the waterfall and audio is out of sync, and also sometimes when i restart the software with the rx888 mk2 i get stutters (but thats only after the first run and then closing the software and opening it again and then its until reboot, dont know if its a problem on my side, could be). But the underrun makes the audio out of sync even tho the waterfall runs all the time. Im using Wireless Connection now but it should be fast enough (80mbit/s upload). It also only happens one time and then its out of sync all the time even for new users (when reloading the site). Moving to an station just takes very long for the audio to be really there.

**Comment by Steven9101** [comment]
So i mean the waterfall works fine but the audio is not in sync with the waterfall (the waterfall is earlier)

**Comment by Steven9101** [comment]
Btw, managed to get FT8 going using WASM. The code isn't clean yet + you probably will implement it in your decoder library so i dont think of doing an PR. 
![chrome_tfyEe5lSiY](https://github.com/PhantomSDR/PhantomSDR/assets/164558083/d9c92081-3a0f-4599-8c33-112949058fd7)

**Comment by rhgndf** [comment]
The audio issue is a buffering issue. I have fixed one bug and reduced the audio buffering.

For the FT8 WASM, what library did you use? I once integrated ft8_lib but I think there needs to be some thought on time synchronization, like taking into account of the network latency from the backend to the frontend. Maybe for this the server timestamp could be sent alongside the audio packets? I tried also coding a weak signal library in rhgndf/weaksignal, to hopefully integrate it with the decoders package.

**Comment by rhgndf** [comment]
Also, I appreciate the bug reports, since I don't have a huge variety of hardware to test out every possible hardware combination and network setup, so I have to rely on best guesses on whether it might work on other setups. Additionally, I figured out I could use a far away VPN to connect back to my local network to simulate high latency users.

**Comment by Steven9101** [comment]
I used https://github.com/e04/ft8js/tree/main

I think synchronization could be done by doing some pings regularly and adding that into account to run it with the timestamps, but most likely it wont matter that much because we are talking not seconds but milliseconds, it will make some signals unusable but not all and most will still be decoded. But the simplest would probably doing an ping and average it over some time and add that to the 15 second timing. Yea, ill just try to find as many issues to fix (most of them i dont search i just regularly come across them and do an issue to get it fixed for the best experience). But yea, you are right its hard to test yourself probably. But its running really well. I can do the full 128mhz of the rx888 easily with GPU using an Rx580 only. I have stronger gpus here but if the rx580 enough ill stick to it.

**Comment by Steven9101** [comment]
As youve probably seen i also added statistics because i find it cool to see the network usage, cpu usage and gpu usage. But its hard to implement it for everybody especially network and gpu because of the interface names and the brand of gpu

**Comment by Steven9101** [comment]
With the current configuration with 128 MHz (64 MHz of real data), I see a base load of 50–65% on the RX580 and about 2-3% on the CPU and then per user, it's basically nothing, so it could handle many users. I think the network will bottleneck way before the GPU or CPU will. Probably like 200 users and then the network bottlenecks. I think there is also a possibility we can even further reduce the data going to the client. Ill probably look into that next, as websdr.org also has very low network usage.

**Comment by rhgndf** [comment]
Yeah you are right that there's no need for a strong GPU yet. The RX888 should be the highest data rate SDR that is easily accessible. The R9 280X that I'm using works decently, and to reduce the RF noise I have it locked to the lowest gpu and memory clock. It uses around 90% of the GPU but it runs really cool. I think an even weaker R7 240 might work if clocked at the highest frequency, but I haven't really tested it yet.

I did try to optimize the bandwidth a bit. I just did a measurement, at 48kHz audio sampling rate and 2048 max waterfall width, the total network bandwidth is at around 20-30Kbits so around 3-4KBytes/s. That is around 3000 users at a 100Mbit connection. Also, this is around 2x the websdr bandwidth, but the audio bandwidth is higher and the waterfall is wider, so I think its an acceptable tradeoff. If you like to approach that bandwidth you can reduce the audio rate to 24k or 12k and 1024 max waterfall width.

There are some ideas still around in the code, but currently disabled like using lossy codecs like opus on the audio side and treating the waterfall like a video and streaming the video frames, and its possible to get it down to 8Kbit/s or 1Kbyte/s or even lower, but I don't think its worth the complexity unless the use case is like hosting through a very constrained network connection like a mobile internet link.

**Comment by rhgndf** [comment]
About the additional features:

The statistics is nice, but I haven't really found a cross platform way to do it on multiple OSes, so the consideration is how to not increase the complexity and maintenance burden too much.

The wire format for the frontend might need to change if the timestamp thing were to be implemented, since the format is just appending raw bytes to the main payload, which may not be extensible. Maybe a cbor format would be suitable.

**Comment by rhgndf** [comment]
It turns out the measurement program I have been using is inaccurate, it is around 60-70kB/s for this application and 10kB/s for websdr.org. Have updated the original post.

**Comment by Steven9101** [comment]
I think for ssb you should probably only send like 8-10khz and for am 20khz and for fm 48khz that would be better for bandwidth but also more complex. The use case for lower network usage would only be the high amount of users that it could handle then. Ill try later with the parameters maybe i can get it down to 80-100kbit/s which should be fine

**Comment by Steven9101** [comment]
And about the statistics yea that is correct, cpu usage should be no problem for multiple oses but gpu and network will be.

**Comment by rhgndf** [comment]
The codec seems to be doing a good job adapting the bitrate already. On SSB mode at 48kHz sampling, the bandwidth goes from below 30KB/s at 3kHz passband to 70KB/s at the full 24kHz passband. When you optimize the sampling rate, one thing to take into account is that whether you want your users to decode DRM radio, which might take more bandwidth. 

Maybe the waterfall can be encoded with ADPCM which should halve the bandwidth and reduce the total by 8KB/s at 2048 width.

**Comment by rhgndf** [comment]
There's two additional things you can try to reduce audio bandwidth:

https://github.com/PhantomSDR/PhantomSDR/blob/c6139784f601607bc844b1fcf95f45a0f3c69da8/src/signal.cpp#L22
Change this to a higher number, to make the encoder try harder to compress the stream. Up to 8 is possible. This of course will increase CPU usage.

https://github.com/PhantomSDR/PhantomSDR/blob/c6139784f601607bc844b1fcf95f45a0f3c69da8/src/signal.cpp#L281
Reduce the amount of audio bits sent, changing from `/ 4` to `/ 8` or `/ 16` will decrease bandwidth at the expense of audio quality.

**Comment by Steven9101** [comment]
To come back to the underrun, i still appear to have this issue even with the reduced buffering. Theres one underrun and then its out of sync again

**Comment by rhgndf** [comment]
How out of sync is it? This might be due to network variability, where once it underruns, the application tries to buffer more in order to hide the jitter of when the audio packets arrive. I set the window length to be around 10 seconds, so after a while the application detects no jitter and brings the audio forward again.

**Comment by rhgndf** [comment]
Thinking about it, this might be the server side buffer, since you reported that new users also have the issue. This commit b83c683 reduces it.

**Comment by Steven9101** [comment]
No, i just tried it and its still there, also got the network usage down to below 200 kbit/s (25kb/s) for now, before i was running 100mhz at 50kb/s. Dont think i can tweak it more without losing functionality i guess. Its running like 130-200kbit/s (16-25kb/s) now per user with 100mhz (50mhz real). In the client it says underrun and then it has a long delay i think it differs but sometimes the delay is probably like 500ms to 2 seconds of what the waterfall currently shows, that makes the tuning so delayed.

**Comment by Steven9101** [comment]
I think it only happens on new client as the same issue happens again on them in client side that it underruns and then has that delay. Dont think its an server side issue

**Comment by rhgndf** [comment]
I think I might have another idea: I forgot to set a lower limit on the buffering, I set it to 0.25 now: b83c683. Are you using the browser on the same machine as the server is on?

**Comment by Steven9101** [comment]
No, the browser is on a different machine. As said its connect with wifi, it has like 20ms of ping and enough upload (80-100mbit/s)

**Comment by Steven9101** [comment]
No sadly it still happens. I load the page i hear audio for a small period of time then it underruns 1 or 2 times then i just have to wait a long period of time until the audio plays again and then its delayed

**Comment by rhgndf** [comment]
That is weird. I will need to figure out how to replicate it. On my setup, I am doing the same, with wifi and it doesn't happen.

**Comment by Steven9101** [comment]
Yea its weird, i also dont know how you could replicate it. Ill try to find out whats causing it

**Comment by rhgndf** [comment]
If that still doesn't work I might consider adding a fixed 1s latency to both waterfall and audio streams to sync. The signals will look lagged behind but at least it isn't out of sync.

**Comment by Steven9101** [comment]
Yep that seems better, atleast on the first try i didnt get the issue i had earlier

**Comment by Steven9101** [comment]
I still got the underrun but now it doesnt has the issue of delay

**Comment by rhgndf** [comment]
I'm looking into whether getting rid of the adaptive buffering and just doing a fixed 1s buffer will help things.

**Comment by Steven9101** [comment]
yea but then tuning will be delayed
