### ISSUE TITLE
CW frequency is the BFO frequency not listened-to frequency

### ISSUE THREAD

**Issue by sblandford** [PhantomSDR/PhantomSDR#9]
In CW mode the frequency displayed makes most sense if it is the frequency being listened to e.g. if I want to listen to MSF on 60KHz or the time standard on 10MHz I would expect to enter those exact numbers as the frequency rather than have to manually calculate a 700Hz offset to hear them.

**Comment by rhgndf** [comment]
I think for this is it a bit difficult to fix a specific offset. I searched for whether there is a standardised offset and I have seen numbers from 600Hz to 1kHz. Would an input that specifies the offset be better?

**Comment by Steven9101** [comment]
But for msf and dcf77 there has to be a 500hz shift so its really not consistent.

**Comment by sblandford** [comment]
It's not consistent because it depends on the CW filter. On KiwiSDR the narrow CW filter has a 500 Hz offset and the wide CW filter has a 1.6KHz offset. The ICOM-705 has a 700Hz offset regardless of CW bandwidth.

I guess the main requirement is that when a frequency is selected you hear what you went there for.

**Comment by rhgndf** [comment]
I implemented it here: d9b4df2, along with some improvements to the frequency input component. Now, for both CW-U and CW-L, the BFO makes both behave exactly the same for signals which are exactly on target.

**Comment by rhgndf** [comment]
I just realised I typed 700 and not 750. I took a look and some SDR software do allow changing the offset.

**Comment by rhgndf** [comment]
Fixed a bug when BFO is active for clicking in [aff02e6](https://github.com/PhantomSDR/frontend/commit/aff02e6a8892c4db57e0803579fab0c8f48fc663)

**Comment by sblandford** [comment]
Just re-compiled and checked. CW mode is now correctly working as expected with a 700Hz tone audible from a carrier at the selected frequency.
